Task3
VladislavKhodoruk/food_delivery_app pull request #3
Opened 2023-08-27 18:31 UTC by VladislavKhodoruk

State management & Cart page

2023-08-28 13:52 UTC, dungeon-slave requested changes

2023-08-28 13:52 UTC, dungeon-slave commented on core_ui/lib/src/theme/app_theme.dart
> +            borderRadius: BorderRadius.circular(5),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on core_ui/lib/src/theme/app_theme.dart
> +            borderRadius: BorderRadius.circular(5),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/entities/cart_item/cart_item_entity.freezed.dart
> +// coverage:ignore-file
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/entities/cart_item/cart_item_entity.dart
> +
remove enter

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/entities/cart_item/cart_item_entity.dart
> +
remove enter

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/entities/product/product_entity.freezed.dart
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/mappers/cart_items_mapper.dart
> +
remove enter

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +    final Box<CartItemEntity> box = await Hive.openBox(LocalConstants.cartBox);
open once when start program

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +    final Box<CartItemEntity> box = await Hive.openBox(LocalConstants.cartBox);
same

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +    final Box<CartItemEntity> box = await Hive.openBox(LocalConstants.cartBox);
same

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/repositories/cart_repository_impl.dart
> +          (e) => CartItemsMapper.toModel(e),
type

2023-08-28 13:52 UTC, dungeon-slave commented on data/pubspec.lock
>        url: "https://pub.dev"
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on domain/lib/models/cart_item/cart_item_model.freezed.dart
> +// coverage:ignore-file
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on domain/pubspec.lock
>      dependency: transitive
all *lock, *g, *freezed in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/bloc/cart/cart_bloc.dart
> +        .indexWhere((item) => item.product.id == eventCartItem.product.id);
type

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/bloc/cart/cart_bloc.dart
> +    final int index = newItems
refactor (?)

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/bloc/cart/cart_bloc.dart
> +    final CartItemModel newItem =
refactor (?)

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/cart_screen.dart
> +              left: 18,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/cart_screen.dart
> +              separatorBuilder: (_, __) => const SizedBox(height: 11),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/cart_screen.dart
> +            toolbarHeight: 65,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +            top: 7,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +              left: 6,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                width: 1,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                    height: 55,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                  borderRadius: BorderRadius.circular(5),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                const SizedBox(width: 7),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                    maxLines: 2,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                const SizedBox(width: 7),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                          size: 22,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                    const SizedBox(width: 3),
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                      height: 22,
hardcoded

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                    const SizedBox(width: 3),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +          right: 0,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/cart_item.dart
> +                          size: 22,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/price_label.dart
> +            spreadRadius: 0,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/price_label.dart
> +        horizontal: 5,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/widgets/price_label.dart
> +          width: 1,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/pubspec.lock
>      dependency: transitive
lock in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/bloc/details/details_bloc.dart
> +      required CartItemModel cartItem})
,

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/bloc/details/details_bloc.dart
> +    if (newItem.amount > 0) {
refactor (?)

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +  final CartItemModel cartItem;
private

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +              toolbarHeight: 65,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                          padding: const EdgeInsets.only(bottom: 70),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                                    borderRadius: BorderRadius.circular(5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                                    top: 10,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                              const SizedBox(height: 15),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                              const SizedBox(height: 15),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                                indent: 20,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                              const SizedBox(height: 15),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                                  spacing: 8.0, // gap between adjacent chips
hc + remove comments

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +      height: 45,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +          size: 30,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +      height: 45,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +            flex: 3,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                  size: 30,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +            flex: 2,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +              color: theme.scaffoldBackgroundColor.withOpacity(0.7),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +            flex: 3,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/details_screen.dart
> +                  size: 30,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/widgets/text_label.dart
>          vertical: 2,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/details/lib/src/ui/widgets/text_label.dart
>          borderRadius: BorderRadius.circular(5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/bloc/home/home_bloc.dart
> +    if (topRouteName == 'HomeRoute') {
hc?

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/bloc/home/home_bloc.dart
> +          .map((product) => CartItemModel(product: product, amount: 0))
type

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/bloc/home/home_bloc.dart
> +    final int index = newItems
refactor ?

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/bloc/home/home_bloc.dart
> +    final CartItemModel newItem =
refactor?

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/home_screen.dart
> +            toolbarHeight: 65,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/home_screen.dart
> +                padding: const EdgeInsets.only(right: 4),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +            spreadRadius: 0,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
>        padding: const EdgeInsets.all(5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +          Radius.circular(5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +                    const SizedBox(width: 5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +                              height: 28,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +                          const SizedBox(width: 5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +                          const SizedBox(width: 5),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/ui/widgets/product_item.dart
> +                        height: 28,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/pubspec.lock
>        url: "https://pub.dev"
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on features/main/lib/src/ui/widgets/cart_button.dart
> +                        padding: const EdgeInsets.symmetric(horizontal: 2),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/main/lib/src/ui/widgets/cart_button.dart
> +                          borderRadius: BorderRadius.circular(7),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/main/pubspec.lock
>      dependency: transitive
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on features/settings/lib/src/ui/settings_screen.dart
>                          const SizedBox(width: 10),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/settings/lib/src/ui/settings_screen.dart
>                          const SizedBox(width: 10),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on ios/Podfile.lock
>    - BoringSSL-GRPC/Implementation (0.0.24):
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on ios/Runner.xcodeproj/project.pbxproj
>  		97C146E61CF9000F007C117D /* Project object */ = {
in gitignore (?)

2023-08-28 13:52 UTC, dungeon-slave commented on pubspec.lock
>      dependency: transitive
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on core/pubspec.lock
>      dependency: transitive
in gitignore

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +  Future<void> addCartItem(CartItemEntity cartItem) async {
unnecessary async

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +  Future<void> deleteCartItem(CartItemEntity cartItem) async {
same

2023-08-28 13:52 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
> +  Future<List<CartItemEntity>> getAllCartItems() async {
same

2023-08-28 13:52 UTC, dungeon-slave commented on domain/lib/usecases/delete_all_cart_items_from_storage.dart
> +  Future<void> execute(NoParams input) async {
unnecessary async

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/bloc/cart/cart_bloc.dart
> +
remove enter

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/bloc/cart/cart_bloc.dart
> +    final int index = newItems.indexWhere((CartItemModel currentCartItem) =>
refactor?

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/cart_screen.dart
> +          separatorBuilder: (_, __) => const SizedBox(height: 11),
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/cart/lib/src/ui/cart_screen.dart
> +            height: 45,
hc

2023-08-28 13:52 UTC, dungeon-slave commented on features/home/lib/src/bloc/home/home_bloc.dart
> +    final int index = newItems.indexWhere((CartItemModel currentCartItem) =>
refactor (?)

2023-08-28 14:49 UTC, Alexey-Lebedzeu requested changes

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on data/lib/entities/product/product_entity.dart
> +@HiveType(typeId: 0, adapterName: 'ProductEntityAdapter')
name?

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on data/lib/mappers/cart_items_mapper.dart
> +
organize imports

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on data/lib/providers/remote/api_provider.dart
> +          (QueryDocumentSnapshot<Map<String, dynamic>> e) =>
naming

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on data/lib/repositories/cart_repository_impl.dart
> +          (e) => CartItemsMapper.toModel(e),
naming

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on domain/lib/usecases/get_all_cart_items_from_storage.dart
> +  Future<List<CartItemModel>> execute(NoParams input) async {
async ?

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/cart/lib/src/bloc/cart/cart_state.dart
> +    this.cartItems = const [],
type

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/cart/lib/src/ui/widgets/price_label.dart
> +            offset: const Offset(0, 2), // changes position of shadow
comment?

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/details/lib/src/ui/details_screen.dart
> +          onPanUpdate: (details) {
type

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/details/lib/src/ui/details_screen.dart
> +                    slivers: [
type

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/details/lib/src/ui/details_screen.dart
> +                onPressed: () => Navigator.pop(context),
auto route? to bloc

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/details/lib/src/ui/details_screen.dart
> +                                          horizontal: 5),
, HC

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/home/lib/src/bloc/home/home_bloc.dart
> +    final List<CartItemModel> synchronizedCartItems = cartItems.map((cartItem) {
type

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/home/lib/src/bloc/home/home_state.dart
> +    this.cartItems = const [],
type

2023-08-28 14:49 UTC, Alexey-Lebedzeu commented on features/main/lib/src/bloc/main/main_bloc_observer.dart
> +  BuildContext context;
bloc

2023-08-30 09:44 UTC, VladislavKhodoruk commented
https://github.com/VladislavKhodoruk/food_delivery_app/assets/97263192/a59ffaf6-495b-48b0-a1cf-de8ec159f2d8

2023-08-30 09:47 UTC, merged